export const COUPANG_ACTION_LABELS = {
  updateOptionPricesBulk: "상품 옵션 가격 변경",
  updateOptionQuantitiesBulk: "상품 옵션 재고 변경",
  updateOptionSaleStatusesBulk: "상품 옵션 판매상태 변경",
  updatePartialProduct: "배송/반품 수정",
  updateFullProduct: "상품 전체 수정",
  updatePrice: "가격 변경",
  updateQuantity: "재고 변경",
  updateSaleStatus: "판매상태 변경",
  markPreparing: "상품준비중 처리",
  cancelOrder: "주문 취소",
  uploadInvoice: "송장 업로드",
  updateInvoice: "송장 수정",
  stopShipment: "출고중지완료 처리",
  markAlreadyShipped: "이미출고 처리",
  confirmReturnInbound: "반품 입고 확인",
  approveReturn: "반품 승인",
  uploadReturnCollectionInvoice: "회수 송장 등록",
  confirmExchangeInbound: "교환 입고 확인",
  rejectExchange: "교환 거부",
  uploadExchangeInvoice: "교환상품 송장 업로드",
} as const;
