import type {
  CoupangExchangeDetailResponse,
  CoupangExchangeRow,
  CoupangOrderDetailResponse,
  CoupangOrderListResponse,
  CoupangProductListResponse,
  CoupangReturnDetailResponse,
  CoupangReturnRow,
  CoupangSettlementListResponse,
  CoupangSettlementRow,
  CoupangSimpleListResponse,
  CoupangStoreRef,
} from "@shared/coupang";

const store: CoupangStoreRef = {
  id: "fallback-coupang",
  name: "쿠팡 샘플 스토어",
  vendorId: "A00000000",
};

export function getSampleCoupangProducts(): CoupangProductListResponse {
  return {
    store,
    items: [
      {
        sellerProductId: "30100201234",
        sellerProductName: "KIKIT 텀블러 500ml",
        vendorId: store.vendorId,
        displayCategoryCode: "194176",
        displayCategoryName: "주방용품 > 텀블러",
        brand: "KIKIT",
        statusName: "승인완료",
        saleStartedAt: "2026-03-20T09:00:00+09:00",
        saleEndedAt: null,
        createdAt: "2026-03-20T09:00:00+09:00",
        lastModifiedAt: "2026-03-23T18:10:00+09:00",
        vendorItems: [
          {
            vendorItemId: "7039748123",
            itemName: "레드",
            externalVendorSku: "OPT-1001-RED",
            originalPrice: 15900,
            salePrice: 15400,
            inventoryCount: 21,
            saleStatus: "ONSALE",
            adultOnly: "EVERYONE",
            lastModifiedAt: "2026-03-23T18:10:00+09:00",
            attributes: ["색상: 레드"],
          },
          {
            vendorItemId: "7039748124",
            itemName: "블루",
            externalVendorSku: "OPT-1001-BLUE",
            originalPrice: 15900,
            salePrice: 15400,
            inventoryCount: 9,
            saleStatus: "SUSPENDED",
            adultOnly: "EVERYONE",
            lastModifiedAt: "2026-03-23T18:10:00+09:00",
            attributes: ["색상: 블루"],
          },
        ],
      },
      {
        sellerProductId: "30100209991",
        sellerProductName: "프리미엄 세탁 바구니",
        vendorId: store.vendorId,
        displayCategoryCode: "194992",
        displayCategoryName: "생활용품 > 정리/수납",
        brand: "KIKIT Home",
        statusName: "판매중",
        saleStartedAt: "2026-03-18T09:00:00+09:00",
        saleEndedAt: null,
        createdAt: "2026-03-18T09:00:00+09:00",
        lastModifiedAt: "2026-03-24T10:15:00+09:00",
        vendorItems: [
          {
            vendorItemId: "7039750001",
            itemName: "M",
            externalVendorSku: "OPT-2001-M",
            originalPrice: 18900,
            salePrice: 16900,
            inventoryCount: 15,
            saleStatus: "ONSALE",
            adultOnly: "EVERYONE",
            lastModifiedAt: "2026-03-24T10:15:00+09:00",
            attributes: ["사이즈: M"],
          },
          {
            vendorItemId: "7039750002",
            itemName: "L",
            externalVendorSku: "OPT-2001-L",
            originalPrice: 20900,
            salePrice: 18900,
            inventoryCount: 11,
            saleStatus: "ONSALE",
            adultOnly: "EVERYONE",
            lastModifiedAt: "2026-03-24T10:15:00+09:00",
            attributes: ["사이즈: L"],
          },
        ],
      },
    ],
    nextToken: null,
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "Coupang 실연동 실패로 샘플 상품 데이터를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangOrders(): CoupangOrderListResponse {
  return {
    store,
    items: [
      {
        id: "fallback-order-1",
        shipmentBoxId: "853138991234567890",
        orderId: "19000009511537",
        orderedAt: "2026-03-24T09:10:00+09:00",
        paidAt: "2026-03-24T09:12:00+09:00",
        status: "ACCEPT",
        ordererName: "김고객",
        receiverName: "김고객",
        receiverSafeNumber: "050-1234-5678",
        receiverAddress: "서울특별시 송파구 예시로 10",
        receiverPostCode: "05510",
        productName: "KIKIT 텀블러 500ml / 레드",
        optionName: "레드",
        sellerProductId: "30100201234",
        sellerProductName: "KIKIT 텀블러 500ml",
        vendorItemId: "7039748123",
        externalVendorSku: "OPT-1001-RED",
        quantity: 2,
        salesPrice: 30800,
        orderPrice: 31800,
        discountPrice: 1000,
        cancelCount: 0,
        holdCountForCancel: 0,
        deliveryCompanyName: null,
        deliveryCompanyCode: null,
        invoiceNumber: null,
        invoiceNumberUploadDate: null,
        estimatedShippingDate: "2026-03-25",
        inTransitDateTime: null,
        deliveredDate: null,
        shipmentType: "THIRD_PARTY",
        splitShipping: false,
        ableSplitShipping: false,
        customerServiceIssueCount: 0,
        customerServiceIssueSummary: null,
        customerServiceIssueBreakdown: [],
        customerServiceState: "unknown",
        customerServiceFetchedAt: null,
        availableActions: ["markPreparing"],
      },
      {
        id: "fallback-order-2",
        shipmentBoxId: "853138991234567891",
        orderId: "19000009511538",
        orderedAt: "2026-03-24T11:22:00+09:00",
        paidAt: "2026-03-24T11:23:00+09:00",
        status: "INSTRUCT",
        ordererName: "박주문",
        receiverName: "박주문",
        receiverSafeNumber: "050-3333-2222",
        receiverAddress: "경기도 성남시 예시대로 22",
        receiverPostCode: "13494",
        productName: "프리미엄 세탁 바구니 / L",
        optionName: "L",
        sellerProductId: "30100209991",
        sellerProductName: "프리미엄 세탁 바구니",
        vendorItemId: "7039750002",
        externalVendorSku: "OPT-2001-L",
        quantity: 1,
        salesPrice: 18900,
        orderPrice: 18900,
        discountPrice: 0,
        cancelCount: 0,
        holdCountForCancel: 0,
        deliveryCompanyName: null,
        deliveryCompanyCode: null,
        invoiceNumber: null,
        invoiceNumberUploadDate: null,
        estimatedShippingDate: "2026-03-25",
        inTransitDateTime: null,
        deliveredDate: null,
        shipmentType: "THIRD_PARTY",
        splitShipping: false,
        ableSplitShipping: false,
        customerServiceIssueCount: 0,
        customerServiceIssueSummary: null,
        customerServiceIssueBreakdown: [],
        customerServiceState: "unknown",
        customerServiceFetchedAt: null,
        availableActions: ["uploadInvoice"],
      },
    ],
    nextToken: null,
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "Coupang 주문 API 연결 실패로 샘플 주문 데이터를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangOrderDetail(): CoupangOrderDetailResponse {
  const baseList = getSampleCoupangOrders();

  return {
    store,
    item: {
      shipmentBoxId: "853138991234567890",
      orderId: "19000009511537",
      orderedAt: "2026-03-24T09:10:00+09:00",
      paidAt: "2026-03-24T09:12:00+09:00",
      status: "ACCEPT",
      orderer: {
        name: "김고객",
        email: "sample@example.com",
        safeNumber: "050-1234-5678",
        ordererNumber: null,
      },
      receiver: {
        name: "김고객",
        safeNumber: "050-1234-5678",
        receiverNumber: null,
        addr1: "서울특별시 송파구 예시로 10",
        addr2: "101동 1201호",
        postCode: "05510",
      },
      deliveryCompanyName: null,
      deliveryCompanyCode: null,
      invoiceNumber: null,
      inTransitDateTime: null,
      deliveredDate: null,
      parcelPrintMessage: "부재 시 문 앞에 놓아주세요.",
      shipmentType: "THIRD_PARTY",
      splitShipping: false,
      ableSplitShipping: false,
      items: [baseList.items[0]],
      relatedReturnRequests: [],
      relatedExchangeRequests: [],
    },
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "Coupang 단건 주문 조회 실패로 샘플 상세를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangReturns(): CoupangSimpleListResponse<CoupangReturnRow> {
  return {
    store,
    items: [
      {
        id: "fallback-return-1",
        receiptId: "50000111",
        orderId: "19000009511537",
        status: "RETURNS_UNCHECKED",
        cancelType: "RETURN",
        receiptType: "RETURN",
        returnDeliveryType: "MANUAL",
        releaseStatus: "N",
        releaseStatusName: "미출고",
        productName: "KIKIT 텀블러 500ml / 레드",
        sellerProductId: "30100201234",
        sellerProductName: "KIKIT 텀블러 500ml",
        vendorItemId: "7039748123",
        vendorItemName: "레드",
        shipmentBoxId: "853138991234567890",
        purchaseCount: 2,
        cancelCount: 1,
        createdAt: "2026-03-24T12:00:00+09:00",
        modifiedAt: "2026-03-24T12:30:00+09:00",
        completeConfirmDate: null,
        completeConfirmType: null,
        reasonCode: "CHANGEMIND",
        reason: "필요 없어짐 (단순 변심)",
        faultByType: "BUYER",
        preRefund: false,
        requesterName: "김고객",
        requesterPhone: "02-1234-5678",
        requesterMobile: "010-2222-3333",
        requesterAddress: "서울특별시 송파구 예시로 10 101동 1201호",
        requesterPostCode: "05510",
        deliveryCompanyCode: "CJGLS",
        deliveryInvoiceNo: null,
        retrievalChargeAmount: 3000,
        canMarkShipmentStopped: true,
        canMarkAlreadyShipped: true,
        canApproveReturn: false,
        canConfirmInbound: true,
        canUploadCollectionInvoice: true,
      },
      {
        id: "fallback-return-2",
        receiptId: "50000112",
        orderId: "19000009511539",
        status: "VENDOR_WAREHOUSE_CONFIRM",
        cancelType: "RETURN",
        receiptType: "RETURN",
        returnDeliveryType: "MANUAL",
        releaseStatus: "Y",
        releaseStatusName: "출고 완료",
        productName: "프리미엄 세탁 바구니 / M",
        sellerProductId: "30100209991",
        sellerProductName: "프리미엄 세탁 바구니",
        vendorItemId: "7039750001",
        vendorItemName: "M",
        shipmentBoxId: "853138991234567892",
        purchaseCount: 1,
        cancelCount: 1,
        createdAt: "2026-03-23T14:10:00+09:00",
        modifiedAt: "2026-03-24T09:10:00+09:00",
        completeConfirmDate: "2026-03-24T09:05:00+09:00",
        completeConfirmType: "VENDOR",
        reasonCode: "DEFECT",
        reason: "제품 불량",
        faultByType: "SELLER",
        preRefund: false,
        requesterName: "박주문",
        requesterPhone: null,
        requesterMobile: "010-5555-6666",
        requesterAddress: "경기도 성남시 예시대로 22",
        requesterPostCode: "13494",
        deliveryCompanyCode: "CJGLS",
        deliveryInvoiceNo: "363600001112",
        retrievalChargeAmount: 0,
        canMarkShipmentStopped: false,
        canMarkAlreadyShipped: false,
        canApproveReturn: true,
        canConfirmInbound: false,
        canUploadCollectionInvoice: false,
      },
    ],
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "반품 API 연결 실패로 샘플 케이스를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangReturnDetail(): CoupangReturnDetailResponse {
  const rows = getSampleCoupangReturns().items;

  return {
    store,
    item: {
      receiptId: "50000111",
      orderId: "19000009511537",
      status: "RETURNS_UNCHECKED",
      cancelType: "RETURN",
      receiptType: "RETURN",
      returnDeliveryType: "MANUAL",
      completeConfirmDate: null,
      completeConfirmType: null,
      createdAt: "2026-03-24T12:00:00+09:00",
      modifiedAt: "2026-03-24T12:30:00+09:00",
      reasonCode: "CHANGEMIND",
      reason: "필요 없어짐 (단순 변심)",
      faultByType: "BUYER",
      preRefund: false,
      requester: {
        name: "김고객",
        phone: "02-1234-5678",
        mobile: "010-2222-3333",
        postCode: "05510",
        address: "서울특별시 송파구 예시로 10",
        addressDetail: "101동 1201호",
      },
      returnCharge: {
        amount: 3000,
        rawText: "회수비 3,000원",
      },
      items: [
        {
          vendorItemId: "7039748123",
          vendorItemName: "레드",
          sellerProductId: "30100201234",
          sellerProductName: "KIKIT 텀블러 500ml",
          shipmentBoxId: "853138991234567890",
          purchaseCount: 2,
          cancelCount: 1,
          releaseStatus: "N",
          releaseStatusName: "미출고",
        },
      ],
      deliveries: [
        {
          deliveryCompanyCode: "CJGLS",
          deliveryInvoiceNo: null,
          returnDeliveryId: "25726758",
          returnExchangeDeliveryType: "RETURN",
          regNumber: null,
        },
      ],
      summaryRow: rows[0],
    },
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "단건 반품 조회 실패로 샘플 상세를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangExchanges(): CoupangSimpleListResponse<CoupangExchangeRow> {
  return {
    store,
    items: [
      {
        exchangeId: "70000101",
        orderId: "19000009511538",
        status: "PROGRESS",
        orderDeliveryStatusCode: "DELIVERED",
        collectStatus: "CompleteCollect",
        collectCompleteDate: "2026-03-24T13:40:00+09:00",
        createdAt: "2026-03-24T13:00:00+09:00",
        modifiedAt: "2026-03-24T13:40:00+09:00",
        reasonCode: "DAMAGED",
        reason: "파손 교환 요청",
        reasonDetail: "손잡이 파손",
        productName: "프리미엄 세탁 바구니 / L",
        vendorItemId: "7039750002",
        vendorItemName: "L",
        sellerProductId: "30100209991",
        sellerProductName: "프리미엄 세탁 바구니",
        shipmentBoxId: "853138991234567893",
        originalShipmentBoxId: "853138991234567891",
        quantity: 1,
        returnCustomerName: "박주문",
        returnMobile: "010-5555-6666",
        returnAddress: "경기도 성남시 예시대로 22",
        deliveryCustomerName: "박주문",
        deliveryMobile: "050-3333-2222",
        deliveryAddress: "경기도 성남시 예시대로 22",
        deliverCode: null,
        invoiceNumber: null,
        canConfirmInbound: true,
        canReject: true,
        canUploadExchangeInvoice: true,
      },
    ],
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "교환 API 연결 실패로 샘플 데이터를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangExchangeDetail(): CoupangExchangeDetailResponse {
  const row = getSampleCoupangExchanges().items[0];

  return {
    store,
    item: {
      exchangeId: row.exchangeId,
      orderId: row.orderId,
      status: row.status,
      orderDeliveryStatusCode: row.orderDeliveryStatusCode,
      collectStatus: row.collectStatus,
      collectCompleteDate: row.collectCompleteDate,
      createdAt: row.createdAt,
      modifiedAt: row.modifiedAt,
      reasonCode: row.reasonCode,
      reason: row.reason,
      reasonDetail: row.reasonDetail,
      requester: {
        name: "박주문",
        phone: null,
        mobile: "010-5555-6666",
        postCode: "13494",
        address: "경기도 성남시 예시대로 22",
        addressDetail: "301동 505호",
        memo: "오후 수거 요청",
      },
      recipient: {
        name: "박주문",
        phone: null,
        mobile: "050-3333-2222",
        postCode: "13494",
        address: "경기도 성남시 예시대로 22",
        addressDetail: "301동 505호",
        memo: "새 상품은 문 앞에 두세요.",
      },
      items: [
        {
          vendorItemId: "7039750002",
          vendorItemName: "L",
          orderItemName: "프리미엄 세탁 바구니 / L",
          targetItemName: "프리미엄 세탁 바구니 / 새상품 L",
          quantity: 1,
          shipmentBoxId: "853138991234567893",
          releaseStatus: "Y",
          collectStatus: "CompleteCollect",
        },
      ],
      invoices: [
        {
          shipmentBoxId: "853138991234567893",
          orderId: "19000009511538",
          orderType: "EXCHANGE",
          shippingDeliveryType: "EXCHANGE_DELIVERY",
          invoiceNumber: null,
          estimatedDeliveryDate: "2026-03-26T00:00:00",
          deliveredDate: null,
          statusCode: "INSTRUCT",
          deliverCode: null,
          invoiceNumberUploadDate: null,
          invoiceModifiable: true,
        },
      ],
      summaryRow: row,
    },
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "단건 교환 조회 실패로 샘플 상세를 표시합니다.",
    source: "fallback",
  };
}

export function getSampleCoupangSettlements(): CoupangSettlementListResponse {
  const items: CoupangSettlementRow[] = [
    {
      settlementId: "ST-20260324-01",
      orderId: "19000009511537",
      saleType: "SALE",
      saleDate: "2026-03-17",
      recognitionDate: "2026-03-24",
      settlementDate: "2026-04-02",
      finalSettlementDate: "2026-04-09",
      productName: "KIKIT 텀블러 500ml / 레드",
      vendorItemName: "레드",
      vendorItemId: "7039748123",
      externalSellerSkuCode: "OPT-1001-RED",
      quantity: 2,
      salesAmount: 30800,
      saleAmount: 30800,
      settlementAmount: 27120,
      serviceFee: 3388,
      serviceFeeVat: 292,
      serviceFeeRatio: 11,
      sellerDiscountCoupon: 0,
      downloadableCoupon: 0,
      deliveryFeeAmount: 0,
      deliveryFeeSettlementAmount: 0,
      taxType: "TAX",
      status: "SALE",
      settledAt: "2026-04-02",
    },
    {
      settlementId: "ST-20260324-02",
      orderId: "19000009511538",
      saleType: "REFUND",
      saleDate: "2026-03-18",
      recognitionDate: "2026-03-24",
      settlementDate: "2026-04-02",
      finalSettlementDate: "2026-04-09",
      productName: "프리미엄 세탁 바구니 / L",
      vendorItemName: "L",
      vendorItemId: "7039750002",
      externalSellerSkuCode: "OPT-2001-L",
      quantity: 1,
      salesAmount: 18900,
      saleAmount: 18900,
      settlementAmount: 16632,
      serviceFee: 2058,
      serviceFeeVat: 210,
      serviceFeeRatio: 10.9,
      sellerDiscountCoupon: 0,
      downloadableCoupon: 0,
      deliveryFeeAmount: 0,
      deliveryFeeSettlementAmount: 0,
      taxType: "TAX",
      status: "REFUND",
      settledAt: "2026-04-02",
    },
  ];

  return {
    store,
    items,
    histories: [
      {
        settlementType: "WEEKLY",
        settlementDate: "2026-04-02",
        revenueRecognitionYearMonth: "2026-03",
        revenueRecognitionDateFrom: "2026-03-24",
        revenueRecognitionDateTo: "2026-03-24",
        totalSale: 49700,
        serviceFee: 5446,
        settlementTargetAmount: 44254,
        settlementAmount: 43752,
        lastAmount: 0,
        pendingReleasedAmount: 0,
        sellerDiscountCoupon: 0,
        downloadableCoupon: 0,
        deductionAmount: 0,
      },
    ],
    summary: {
      rowCount: items.length,
      totalSalesAmount: 49700,
      totalSaleAmount: 49700,
      totalSettlementAmount: 43752,
      totalServiceFee: 5446,
      totalServiceFeeVat: 502,
      totalDeliveryFeeAmount: 0,
      totalDeliverySettlementAmount: 0,
      totalSellerDiscountCoupon: 0,
      totalDownloadableCoupon: 0,
      historySettlementAmount: 43752,
      historyFinalizedAmount: 43752,
    },
    nextToken: null,
    fetchedAt: new Date().toISOString(),
    servedFromFallback: true,
    message: "정산 API 연결 실패로 샘플 정산 데이터를 표시합니다.",
    source: "fallback",
  };
}
